---
- name: Apply existing Kubernetes manifests
  hosts: k8s_control
  gather_facts: false
  become: true
  remote_user: "{{ ansible_user }}"

  tasks:
    - name: Copy namespace.yaml
      copy:
        src: ../k8s/namespace.yaml
        dest: /tmp/namespace.yaml

    - name: Copy deployment.yaml
      copy:
        src: ../k8s/deployment.yaml
        dest: /tmp/deployment.yaml

    - name: Copy service.yaml
      copy:
        src: ../k8s/service.yaml
        dest: /tmp/service.yaml

    - name: Apply Namespace manifest
      shell: kubectl apply -f /tmp/namespace.yaml
      args:
        executable: /bin/bash

    - name: Apply Deployment manifest
      shell: kubectl apply -f /tmp/deployment.yaml
      args:
        executable: /bin/bash

    - name: Apply Service manifest
      shell: kubectl apply -f /tmp/service.yaml
      args:
        executable: /bin/bash


