---
- name: Apply existing Kubernetes manifests
  hosts: k8s_control
  gather_facts: false
  become: true
  remote_user: "{{ ansible_user }}"

  tasks:
    - name: Apply Deployment manifest
      shell: kubectl apply -f /tmp/deployment.yaml
      args:
        executable: /bin/bash

    - name: Apply Service manifest
      shell: kubectl apply -f /tmp/service.yaml
      args:
        executable: /bin/bash

